# ============================================================================
# TradeOS Core Initialization Script
# Auto-generated configuration for full stack deployment
# ============================================================================

Write-Host "🚀 TradeOS Core Initialization" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan

# Check Node.js installation
Write-Host "`n📦 Checking Node.js..." -ForegroundColor Yellow
if (Get-Command node -ErrorAction SilentlyContinue) {
    $nodeVersion = node --version
    Write-Host "✅ Node.js installed: $nodeVersion" -ForegroundColor Green
} else {
    Write-Host "❌ Node.js not found. Please install Node.js 18+" -ForegroundColor Red
    exit 1
}

# Check npm installation
Write-Host "`n📦 Checking npm..." -ForegroundColor Yellow
if (Get-Command npm -ErrorAction SilentlyContinue) {
    $npmVersion = npm --version
    Write-Host "✅ npm installed: $npmVersion" -ForegroundColor Green
} else {
    Write-Host "❌ npm not found" -ForegroundColor Red
    exit 1
}

# Install dependencies
Write-Host "`n📥 Installing dependencies..." -ForegroundColor Yellow
npm install --silent
if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Dependencies installed" -ForegroundColor Green
} else {
    Write-Host "⚠️  Warning: Some dependencies may have issues" -ForegroundColor Yellow
}

# Check for .env file
Write-Host "`n🔐 Checking environment configuration..." -ForegroundColor Yellow
if (Test-Path ".env") {
    Write-Host "✅ .env file found" -ForegroundColor Green
} else {
    Write-Host "⚠️  .env file not found, creating from template..." -ForegroundColor Yellow
    @"
# TradeOS Environment Configuration
# Auto-generated by init-core.ps1

# MongoDB
MONGO_URI=mongodb://localhost:27017/tradeos

# Server
PORT=3001

# Ethereum
PRIVATE_KEY=your_private_key_here
RPC_URL=https://eth-mainnet.g.alchemy.com/v2/your_key

# Solana
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
SOLANA_PRIVATE_KEY=your_solana_private_key_here

# Admin Wallet
ADMIN_WALLET=0x7b861609f4f5977997a6478b09d81a7256d6c748
SOLANA_ADMIN=J7bNrvf26uiWWg8sM43eQMwunaPgmvi7pdRC55CnebPE

# Features
ENABLE_FLASH_LOANS=true
ENABLE_ARBITRAGE=true
ENABLE_GOVERNANCE=true
"@ | Out-File -FilePath ".env" -Encoding UTF8
    Write-Host "✅ .env template created - please update with your keys" -ForegroundColor Green
}

# Verify directory structure
Write-Host "`n📁 Verifying directory structure..." -ForegroundColor Yellow
$requiredDirs = @("contracts", "frontend", "backend", "scripts", "src", "frontend/utils", "frontend/components")
foreach ($dir in $requiredDirs) {
    if (Test-Path $dir) {
        Write-Host "  ✅ $dir" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  Creating $dir..." -ForegroundColor Yellow
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

# Check TypeScript
Write-Host "`n📘 Checking TypeScript..." -ForegroundColor Yellow
if (Test-Path "tsconfig.json") {
    Write-Host "✅ TypeScript configured" -ForegroundColor Green
} else {
    Write-Host "⚠️  tsconfig.json not found" -ForegroundColor Yellow
}

Write-Host "`n✨ Core initialization complete!" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
