#!/bin/bash

# ============================================================================
# TradeOS Full Stack Installation & Deployment Script
# Auto-configures and deploys the entire TradeOS platform
# ============================================================================

set -e  # Exit on error

echo "🚀 TradeOS Full Stack Installation"
echo "===================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check if Node.js is installed
check_node() {
    echo -e "${CYAN}📦 Checking Node.js...${NC}"
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node --version)
        echo -e "${GREEN}✅ Node.js installed: ${NODE_VERSION}${NC}"
    else
        echo -e "${RED}❌ Node.js not found. Please install Node.js 18+${NC}"
        exit 1
    fi
}

# Check if npm is installed
check_npm() {
    echo -e "${CYAN}📦 Checking npm...${NC}"
    if command -v npm &> /dev/null; then
        NPM_VERSION=$(npm --version)
        echo -e "${GREEN}✅ npm installed: ${NPM_VERSION}${NC}"
    else
        echo -e "${RED}❌ npm not found${NC}"
        exit 1
    fi
}

# Create required directories
create_directories() {
    echo -e "\n${CYAN}📁 Creating directory structure...${NC}"
    
    DIRS=(
        "src"
        "frontend/utils"
        "frontend/components/widgets"
        "backend/api"
        "backend/db"
        "scripts"
        "config"
        "tests"
        "docs"
        ".contracts-build"
    )
    
    for dir in "${DIRS[@]}"; do
        if [ ! -d "$dir" ]; then
            mkdir -p "$dir"
            echo -e "${GREEN}  ✅ Created: $dir${NC}"
        else
            echo -e "  ℹ️  Exists: $dir"
        fi
    done
}

# Install Node.js dependencies
install_dependencies() {
    echo -e "\n${CYAN}📥 Installing dependencies...${NC}"
    
    # Main project dependencies
    if [ -f "package.json" ]; then
        echo -e "${YELLOW}Installing main dependencies...${NC}"
        npm install
        echo -e "${GREEN}✅ Main dependencies installed${NC}"
    fi
    
    # Scripts dependencies
    if [ -f "scripts/package.json" ]; then
        echo -e "${YELLOW}Installing script dependencies...${NC}"
        cd scripts
        npm install
        cd ..
        echo -e "${GREEN}✅ Script dependencies installed${NC}"
    fi
}

# Create .env file if it doesn't exist
setup_env() {
    echo -e "\n${CYAN}🔐 Setting up environment configuration...${NC}"
    
    if [ ! -f ".env" ]; then
        cat > .env << 'EOF'
# TradeOS Environment Configuration
# Auto-generated by install-deploy.sh

# MongoDB
MONGO_URI=mongodb://localhost:27017/tradeos

# Server
PORT=3001

# Ethereum
PRIVATE_KEY=your_private_key_here
RPC_URL=https://eth-mainnet.g.alchemy.com/v2/your_key

# Solana
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
SOLANA_PRIVATE_KEY=your_solana_private_key_here

# Admin Wallet
ADMIN_WALLET=0x7b861609f4f5977997a6478b09d81a7256d6c748
SOLANA_ADMIN=J7bNrvf26uiWWg8sM43eQMwunaPgmvi7pdRC55CnebPE

# Features
ENABLE_FLASH_LOANS=true
ENABLE_ARBITRAGE=true
ENABLE_GOVERNANCE=true

# Development
NODE_ENV=development
EOF
        echo -e "${GREEN}✅ .env file created${NC}"
        echo -e "${YELLOW}⚠️  Please update .env with your actual keys${NC}"
    else
        echo -e "${GREEN}✅ .env file already exists${NC}"
    fi
}

# Create symlinks for contracts in src/
link_contracts() {
    echo -e "\n${CYAN}🔗 Creating contract symlinks...${NC}"
    
    if [ -d "contracts" ] && [ -d "src" ]; then
        for contract in contracts/*.sol; do
            if [ -f "$contract" ]; then
                basename=$(basename "$contract")
                if [ ! -L "src/$basename" ]; then
                    ln -sf "../$contract" "src/$basename"
                    echo -e "${GREEN}  ✅ Linked: $basename${NC}"
                fi
            fi
        done
    fi
}

# Build TypeScript files
build_typescript() {
    echo -e "\n${CYAN}🔨 Building TypeScript files...${NC}"
    
    if command -v tsc &> /dev/null && [ -f "tsconfig.json" ]; then
        echo -e "${YELLOW}Compiling TypeScript...${NC}"
        npx tsc --noEmit || echo -e "${YELLOW}⚠️  TypeScript compilation warnings (non-fatal)${NC}"
        echo -e "${GREEN}✅ TypeScript check complete${NC}"
    else
        echo -e "${YELLOW}⚠️  TypeScript compiler not found or tsconfig.json missing${NC}"
    fi
}

# Generate widgets
generate_widgets() {
    echo -e "\n${CYAN}🎨 Generating widgets...${NC}"
    
    if [ -f "create-widget-relay.ts" ]; then
        npx ts-node create-widget-relay.ts \
            --walletConnect \
            --init-swap \
            --bridge \
            --fxGlow \
            --sovereignBadge
        echo -e "${GREEN}✅ Widgets generated${NC}"
    else
        echo -e "${YELLOW}⚠️  create-widget-relay.ts not found${NC}"
    fi
}

# Generate aura map
generate_aura_map() {
    echo -e "\n${CYAN}🗺️  Generating aura map...${NC}"
    
    if [ -f "scripts/auraMap.ts" ]; then
        npx ts-node scripts/auraMap.ts
        echo -e "${GREEN}✅ Aura map generated${NC}"
    else
        echo -e "${YELLOW}⚠️  scripts/auraMap.ts not found${NC}"
    fi
}

# Setup gitignore
setup_gitignore() {
    echo -e "\n${CYAN}📝 Configuring .gitignore...${NC}"
    
    if [ ! -f ".gitignore" ]; then
        cat > .gitignore << 'EOF'
# Dependencies
node_modules/
package-lock.json

# Build outputs
.next/
out/
dist/
docs/
.contracts-build/

# Environment
.env
.env.local
.env.production

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# Test coverage
coverage/

# Temporary files
tmp/
temp/
*.tmp
EOF
        echo -e "${GREEN}✅ .gitignore created${NC}"
    else
        echo -e "  ℹ️  .gitignore already exists"
    fi
}

# Display summary
display_summary() {
    echo -e "\n${CYAN}================================${NC}"
    echo -e "${GREEN}✨ Installation Complete!${NC}"
    echo -e "${CYAN}================================${NC}\n"
    
    echo -e "${YELLOW}Next steps:${NC}"
    echo -e "  1. Update .env with your API keys and private keys"
    echo -e "  2. Start development server: ${GREEN}npm run dev${NC}"
    echo -e "  3. Deploy contracts: ${GREEN}npm run deploy:all${NC}"
    echo -e "  4. Access admin panel at: ${GREEN}http://localhost:3000/adminDashboard${NC}"
    echo -e ""
    echo -e "${YELLOW}Useful commands:${NC}"
    echo -e "  • ${GREEN}npm run build${NC}     - Build for production"
    echo -e "  • ${GREEN}npm run start${NC}     - Start production server"
    echo -e "  • ${GREEN}npm run export${NC}    - Export static site"
    echo -e ""
}

# Main execution
main() {
    check_node
    check_npm
    create_directories
    install_dependencies
    setup_env
    link_contracts
    setup_gitignore
    build_typescript
    generate_widgets
    generate_aura_map
    display_summary
}

main
