/**
 * Auto-generated Bridge Widget
 * Generated by create-widget-relay.ts
 */

import React, { useState } from 'react';

export default function BridgeWidget() {
  const [fromChain, setFromChain] = useState<string>('Ethereum');
  const [toChain, setToChain] = useState<string>('Solana');
  const [amount, setAmount] = useState<string>('');

  const handleBridge = () => {
    console.log(`Bridging ${amount} from ${fromChain} to ${toChain}`);
    // Bridge logic here
  };

  return (
    <div className="bridge-widget">
      <h3>🌉 Cross-Chain Bridge</h3>
      <div className="bridge-form">
        <select value={fromChain} onChange={(e) => setFromChain(e.target.value)}>
          <option>Ethereum</option>
          <option>Solana</option>
          <option>Polygon</option>
          <option>Base</option>
        </select>
        <div>→</div>
        <select value={toChain} onChange={(e) => setToChain(e.target.value)}>
          <option>Solana</option>
          <option>Ethereum</option>
          <option>Polygon</option>
          <option>Base</option>
        </select>
        <input
          type="number"
          placeholder="Amount"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
        />
        <button onClick={handleBridge} className="btn btn-primary">
          Bridge
        </button>
      </div>
    </div>
  );
}
