/**
 * Auto-generated Widget Index
 * Generated by create-widget-relay.ts
 */

export { default as WalletConnectWidget } from './WalletConnectWidget';
export { default as SwapWidget } from './SwapWidget';
export { default as BridgeWidget } from './BridgeWidget';
export { default as FxGlowWidget } from './FxGlowWidget';
export { default as SovereignBadgeWidget } from './SovereignBadgeWidget';
