/**
 * Auto-generated Sovereign Badge Widget
 * Generated by create-widget-relay.ts
 */

import React from 'react';

interface BadgeProps {
  level: number;
  username: string;
}

export default function SovereignBadgeWidget({ level, username }: BadgeProps) {
  const getBadgeColor = (level: number): string => {
    if (level >= 10) return '#FFD700'; // Gold
    if (level >= 5) return '#C0C0C0';  // Silver
    return '#CD7F32'; // Bronze
  };

  return (
    <div className="sovereign-badge-widget">
      <style>{`
        .sovereign-badge {
          display: inline-flex;
          align-items: center;
          padding: 8px 16px;
          border-radius: 20px;
          background: linear-gradient(135deg, ${getBadgeColor(level)}22, ${getBadgeColor(level)}44);
          border: 2px solid ${getBadgeColor(level)};
          color: ${getBadgeColor(level)};
          font-weight: bold;
        }
      `}</style>
      <div className="sovereign-badge">
        <span>🏆</span>
        <span>{username}</span>
        <span>Lv.{level}</span>
      </div>
    </div>
  );
}
