/**
 * Auto-generated Swap Widget
 * Generated by create-widget-relay.ts
 */

import React, { useState } from 'react';

export default function SwapWidget() {
  const [fromToken, setFromToken] = useState<string>('ETH');
  const [toToken, setToToken] = useState<string>('USDC');
  const [amount, setAmount] = useState<string>('');

  const handleSwap = () => {
    console.log(`Swapping ${amount} ${fromToken} for ${toToken}`);
    // Swap logic here
  };

  return (
    <div className="swap-widget">
      <h3>🔄 Swap</h3>
      <div className="swap-form">
        <input
          type="number"
          placeholder="Amount"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
        />
        <select value={fromToken} onChange={(e) => setFromToken(e.target.value)}>
          <option>ETH</option>
          <option>USDC</option>
          <option>USDT</option>
        </select>
        <div>→</div>
        <select value={toToken} onChange={(e) => setToToken(e.target.value)}>
          <option>USDC</option>
          <option>ETH</option>
          <option>USDT</option>
        </select>
        <button onClick={handleSwap} className="btn btn-primary">
          Swap
        </button>
      </div>
    </div>
  );
}
