/**
 * Auto-generated Aura Map Utilities
 * Generated by scripts/auraMap.ts
 */

export interface AuraPoint {
  x: number;
  y: number;
  intensity: number;
  color: string;
}

export interface AuraMap {
  id: string;
  points: AuraPoint[];
  timestamp: number;
}

/**
 * Get aura color based on user level
 */
export function getAuraColorForLevel(level: number): string {
  if (level >= 10) return '#FFD700'; // Gold
  if (level >= 7) return '#7DB5FF';  // Bright blue
  if (level >= 5) return '#4169B0';  // Medium blue
  if (level >= 3) return '#2D4575';  // Dark blue
  return '#1A1F3A'; // Very dark blue
}

/**
 * Calculate aura intensity based on activity
 */
export function calculateAuraIntensity(
  trades: number,
  volume: number,
  lpScore: number
): number {
  const tradeWeight = 0.3;
  const volumeWeight = 0.4;
  const lpWeight = 0.3;
  
  const normalizedTrades = Math.min(trades / 100, 1);
  const normalizedVolume = Math.min(volume / 1000000, 1);
  const normalizedLP = Math.min(lpScore / 100, 1);
  
  return (
    normalizedTrades * tradeWeight +
    normalizedVolume * volumeWeight +
    normalizedLP * lpWeight
  );
}

/**
 * Generate aura gradient for canvas
 */
export function generateAuraGradient(
  ctx: CanvasRenderingContext2D,
  centerX: number,
  centerY: number,
  radius: number,
  intensity: number
): CanvasGradient {
  const gradient = ctx.createRadialGradient(
    centerX, centerY, 0,
    centerX, centerY, radius
  );
  
  const alpha = intensity * 0.8;
  gradient.addColorStop(0, `rgba(125, 181, 255, ${alpha})`);
  gradient.addColorStop(0.5, `rgba(65, 105, 176, ${alpha * 0.6})`);
  gradient.addColorStop(1, `rgba(26, 31, 58, 0)`);
  
  return gradient;
}

/**
 * Apply aura effect to element
 */
export function applyAuraEffect(
  element: HTMLElement,
  intensity: number,
  color?: string
): void {
  const auraColor = color || getAuraColorForLevel(Math.floor(intensity * 10));
  element.style.boxShadow = `0 0 ${20 + intensity * 30}px ${auraColor}`;
  element.style.border = `2px solid ${auraColor}`;
}

/**
 * Default aura map data
 */
export const defaultAuraMap: AuraMap = {
  id: 'default',
  points: [
  {
    "x": 0,
    "y": 0,
    "intensity": 0,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.05,
    "intensity": 0.048685120477977684,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.1,
    "intensity": 0.09446148618625838,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.15,
    "intensity": 0.1368661749183967,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.2,
    "intensity": 0.17537887487646786,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.25,
    "intensity": 0.20943058495790512,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.3,
    "intensity": 0.23842268941360922,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.35,
    "intensity": 0.26175884698832996,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.4,
    "intensity": 0.2788897449072022,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.45,
    "intensity": 0.28936647982240526,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.5,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.55,
    "intensity": 0.28936647982240526,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.6,
    "intensity": 0.2788897449072022,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.65,
    "intensity": 0.26175884698832996,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.7,
    "intensity": 0.23842268941360922,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.75,
    "intensity": 0.20943058495790512,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.8,
    "intensity": 0.17537887487646786,
    "color": "#1a1f3a"
  },
  {
    "x": 0,
    "y": 0.85,
    "intensity": 0.1368661749183967,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.9,
    "intensity": 0.09446148618625838,
    "color": "#0a0e27"
  },
  {
    "x": 0,
    "y": 0.95,
    "intensity": 0.048685120477977684,
    "color": "#0a0e27"
  },
  {
    "x": 0.05,
    "y": 0,
    "intensity": 0.048685120477977684,
    "color": "#0a0e27"
  },
  {
    "x": 0.05,
    "y": 0.05,
    "intensity": 0.10000000000000009,
    "color": "#0a0e27"
  },
  {
    "x": 0.05,
    "y": 0.1,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.05,
    "y": 0.15,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.2,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.25,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.3,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.35,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.4,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.05,
    "y": 0.45,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.05,
    "y": 0.5,
    "intensity": 0.36360389693210726,
    "color": "#2d4575"
  },
  {
    "x": 0.05,
    "y": 0.55,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.05,
    "y": 0.6,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.05,
    "y": 0.65,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.7,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.75,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.8,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.85,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.05,
    "y": 0.9,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.05,
    "y": 0.95,
    "intensity": 0.10000000000000009,
    "color": "#0a0e27"
  },
  {
    "x": 0.1,
    "y": 0,
    "intensity": 0.09446148618625838,
    "color": "#0a0e27"
  },
  {
    "x": 0.1,
    "y": 0.05,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.1,
    "y": 0.1,
    "intensity": 0.19999999999999996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.15,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.2,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.25,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.3,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.35,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.4,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.45,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.5,
    "intensity": 0.434314575050762,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.55,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.6,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.65,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.7,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.1,
    "y": 0.75,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.8,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.85,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.9,
    "intensity": 0.19999999999999996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.1,
    "y": 0.95,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.15,
    "y": 0,
    "intensity": 0.1368661749183967,
    "color": "#0a0e27"
  },
  {
    "x": 0.15,
    "y": 0.05,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.15,
    "y": 0.1,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.15,
    "y": 0.15,
    "intensity": 0.30000000000000004,
    "color": "#1a1f3a"
  },
  {
    "x": 0.15,
    "y": 0.2,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.25,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.3,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.35,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.4,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.45,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.15,
    "y": 0.5,
    "intensity": 0.5050252531694168,
    "color": "#4169b0"
  },
  {
    "x": 0.15,
    "y": 0.55,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.15,
    "y": 0.6,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.65,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.7,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.75,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.8,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.15,
    "y": 0.85,
    "intensity": 0.30000000000000004,
    "color": "#1a1f3a"
  },
  {
    "x": 0.15,
    "y": 0.9,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.15,
    "y": 0.95,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.2,
    "y": 0,
    "intensity": 0.17537887487646786,
    "color": "#1a1f3a"
  },
  {
    "x": 0.2,
    "y": 0.05,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.2,
    "y": 0.1,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.2,
    "y": 0.15,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.2,
    "intensity": 0.4,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.25,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.3,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.35,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.4,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.45,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.5,
    "intensity": 0.5757359312880714,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.55,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.6,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.65,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.2,
    "y": 0.7,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.75,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.8,
    "intensity": 0.4,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.85,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.2,
    "y": 0.9,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.2,
    "y": 0.95,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.25,
    "y": 0,
    "intensity": 0.20943058495790512,
    "color": "#1a1f3a"
  },
  {
    "x": 0.25,
    "y": 0.05,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.25,
    "y": 0.1,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.25,
    "y": 0.15,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.25,
    "y": 0.2,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.25,
    "y": 0.25,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.3,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.35,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.4,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.45,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.5,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.55,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.6,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.65,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.7,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.75,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.25,
    "y": 0.8,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.25,
    "y": 0.85,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.25,
    "y": 0.9,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.25,
    "y": 0.95,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.3,
    "y": 0,
    "intensity": 0.23842268941360922,
    "color": "#1a1f3a"
  },
  {
    "x": 0.3,
    "y": 0.05,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.3,
    "y": 0.1,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.15,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.2,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.25,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.3,
    "intensity": 0.6,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.35,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.4,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.3,
    "y": 0.45,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.3,
    "y": 0.5,
    "intensity": 0.717157287525381,
    "color": "#5a8de0"
  },
  {
    "x": 0.3,
    "y": 0.55,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.3,
    "y": 0.6,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.3,
    "y": 0.65,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.7,
    "intensity": 0.6,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.75,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.3,
    "y": 0.8,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.85,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.9,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.3,
    "y": 0.95,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.35,
    "y": 0,
    "intensity": 0.26175884698832996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.35,
    "y": 0.05,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.35,
    "y": 0.1,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.35,
    "y": 0.15,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.35,
    "y": 0.2,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.25,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.3,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.35,
    "intensity": 0.7,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.4,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.45,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.5,
    "intensity": 0.7878679656440357,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.55,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.6,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.65,
    "intensity": 0.7,
    "color": "#5a8de0"
  },
  {
    "x": 0.35,
    "y": 0.7,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.75,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.8,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.35,
    "y": 0.85,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.35,
    "y": 0.9,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.35,
    "y": 0.95,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.4,
    "y": 0,
    "intensity": 0.2788897449072022,
    "color": "#1a1f3a"
  },
  {
    "x": 0.4,
    "y": 0.05,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.4,
    "y": 0.1,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.4,
    "y": 0.15,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.4,
    "y": 0.2,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.4,
    "y": 0.25,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.4,
    "y": 0.3,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.35,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.4,
    "intensity": 0.8,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.45,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.4,
    "y": 0.5,
    "intensity": 0.8585786437626906,
    "color": "#7db5ff"
  },
  {
    "x": 0.4,
    "y": 0.55,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.4,
    "y": 0.6,
    "intensity": 0.8,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.65,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.7,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.4,
    "y": 0.75,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.4,
    "y": 0.8,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.4,
    "y": 0.85,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.4,
    "y": 0.9,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.4,
    "y": 0.95,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.45,
    "y": 0,
    "intensity": 0.28936647982240526,
    "color": "#1a1f3a"
  },
  {
    "x": 0.45,
    "y": 0.05,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.45,
    "y": 0.1,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.45,
    "y": 0.15,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.2,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.25,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.3,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.45,
    "y": 0.35,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.45,
    "y": 0.4,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.45,
    "y": 0.45,
    "intensity": 0.9,
    "color": "#7db5ff"
  },
  {
    "x": 0.45,
    "y": 0.5,
    "intensity": 0.9292893218813453,
    "color": "#7db5ff"
  },
  {
    "x": 0.45,
    "y": 0.55,
    "intensity": 0.9,
    "color": "#7db5ff"
  },
  {
    "x": 0.45,
    "y": 0.6,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.45,
    "y": 0.65,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.45,
    "y": 0.7,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.45,
    "y": 0.75,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.8,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.85,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.45,
    "y": 0.9,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.45,
    "y": 0.95,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.5,
    "y": 0,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.5,
    "y": 0.05,
    "intensity": 0.36360389693210726,
    "color": "#2d4575"
  },
  {
    "x": 0.5,
    "y": 0.1,
    "intensity": 0.434314575050762,
    "color": "#2d4575"
  },
  {
    "x": 0.5,
    "y": 0.15,
    "intensity": 0.5050252531694168,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.2,
    "intensity": 0.5757359312880714,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.25,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.3,
    "intensity": 0.717157287525381,
    "color": "#5a8de0"
  },
  {
    "x": 0.5,
    "y": 0.35,
    "intensity": 0.7878679656440357,
    "color": "#5a8de0"
  },
  {
    "x": 0.5,
    "y": 0.4,
    "intensity": 0.8585786437626906,
    "color": "#7db5ff"
  },
  {
    "x": 0.5,
    "y": 0.45,
    "intensity": 0.9292893218813453,
    "color": "#7db5ff"
  },
  {
    "x": 0.5,
    "y": 0.5,
    "intensity": 1,
    "color": "#a0d0ff"
  },
  {
    "x": 0.5,
    "y": 0.55,
    "intensity": 0.9292893218813453,
    "color": "#7db5ff"
  },
  {
    "x": 0.5,
    "y": 0.6,
    "intensity": 0.8585786437626906,
    "color": "#7db5ff"
  },
  {
    "x": 0.5,
    "y": 0.65,
    "intensity": 0.7878679656440357,
    "color": "#5a8de0"
  },
  {
    "x": 0.5,
    "y": 0.7,
    "intensity": 0.717157287525381,
    "color": "#5a8de0"
  },
  {
    "x": 0.5,
    "y": 0.75,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.8,
    "intensity": 0.5757359312880714,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.85,
    "intensity": 0.5050252531694168,
    "color": "#4169b0"
  },
  {
    "x": 0.5,
    "y": 0.9,
    "intensity": 0.434314575050762,
    "color": "#2d4575"
  },
  {
    "x": 0.5,
    "y": 0.95,
    "intensity": 0.36360389693210726,
    "color": "#2d4575"
  },
  {
    "x": 0.55,
    "y": 0,
    "intensity": 0.28936647982240526,
    "color": "#1a1f3a"
  },
  {
    "x": 0.55,
    "y": 0.05,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.55,
    "y": 0.1,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.55,
    "y": 0.15,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.2,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.25,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.3,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.55,
    "y": 0.35,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.55,
    "y": 0.4,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.55,
    "y": 0.45,
    "intensity": 0.9,
    "color": "#7db5ff"
  },
  {
    "x": 0.55,
    "y": 0.5,
    "intensity": 0.9292893218813453,
    "color": "#7db5ff"
  },
  {
    "x": 0.55,
    "y": 0.55,
    "intensity": 0.9,
    "color": "#7db5ff"
  },
  {
    "x": 0.55,
    "y": 0.6,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.55,
    "y": 0.65,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.55,
    "y": 0.7,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.55,
    "y": 0.75,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.8,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.85,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.55,
    "y": 0.9,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.55,
    "y": 0.95,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0,
    "intensity": 0.2788897449072022,
    "color": "#1a1f3a"
  },
  {
    "x": 0.6,
    "y": 0.05,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0.1,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0.15,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0.2,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.6,
    "y": 0.25,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.6,
    "y": 0.3,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.35,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.4,
    "intensity": 0.8,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.45,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.6,
    "y": 0.5,
    "intensity": 0.8585786437626906,
    "color": "#7db5ff"
  },
  {
    "x": 0.6,
    "y": 0.55,
    "intensity": 0.841886116991581,
    "color": "#7db5ff"
  },
  {
    "x": 0.6,
    "y": 0.6,
    "intensity": 0.8,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.65,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.7,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.6,
    "y": 0.75,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.6,
    "y": 0.8,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.6,
    "y": 0.85,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0.9,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.6,
    "y": 0.95,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.65,
    "y": 0,
    "intensity": 0.26175884698832996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.65,
    "y": 0.05,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.65,
    "y": 0.1,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.65,
    "y": 0.15,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.65,
    "y": 0.2,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.25,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.3,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.35,
    "intensity": 0.7,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.4,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.45,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.5,
    "intensity": 0.7878679656440357,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.55,
    "intensity": 0.7763932022500211,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.6,
    "intensity": 0.7450490243203608,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.65,
    "intensity": 0.7,
    "color": "#5a8de0"
  },
  {
    "x": 0.65,
    "y": 0.7,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.75,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.8,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.65,
    "y": 0.85,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.65,
    "y": 0.9,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.65,
    "y": 0.95,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.7,
    "y": 0,
    "intensity": 0.23842268941360922,
    "color": "#1a1f3a"
  },
  {
    "x": 0.7,
    "y": 0.05,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.7,
    "y": 0.1,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.15,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.2,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.25,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.3,
    "intensity": 0.6,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.35,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.4,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.7,
    "y": 0.45,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.7,
    "y": 0.5,
    "intensity": 0.717157287525381,
    "color": "#5a8de0"
  },
  {
    "x": 0.7,
    "y": 0.55,
    "intensity": 0.708452405257735,
    "color": "#5a8de0"
  },
  {
    "x": 0.7,
    "y": 0.6,
    "intensity": 0.683772233983162,
    "color": "#5a8de0"
  },
  {
    "x": 0.7,
    "y": 0.65,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.7,
    "intensity": 0.6,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.75,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.7,
    "y": 0.8,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.85,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.9,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.7,
    "y": 0.95,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.75,
    "y": 0,
    "intensity": 0.20943058495790512,
    "color": "#1a1f3a"
  },
  {
    "x": 0.75,
    "y": 0.05,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.75,
    "y": 0.1,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.75,
    "y": 0.15,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.75,
    "y": 0.2,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.75,
    "y": 0.25,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.3,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.35,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.4,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.45,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.5,
    "intensity": 0.6464466094067263,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.55,
    "intensity": 0.639444872453601,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.6,
    "intensity": 0.6192113447068046,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.65,
    "intensity": 0.587689437438234,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.7,
    "intensity": 0.5472307430931291,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.75,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.75,
    "y": 0.8,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.75,
    "y": 0.85,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.75,
    "y": 0.9,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.75,
    "y": 0.95,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.8,
    "y": 0,
    "intensity": 0.17537887487646786,
    "color": "#1a1f3a"
  },
  {
    "x": 0.8,
    "y": 0.05,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.8,
    "y": 0.1,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.8,
    "y": 0.15,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.2,
    "intensity": 0.4,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.25,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.3,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.35,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.4,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.45,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.5,
    "intensity": 0.5757359312880714,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.55,
    "intensity": 0.5698837366478686,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.6,
    "intensity": 0.5527864045000421,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.65,
    "intensity": 0.5256583509747431,
    "color": "#4169b0"
  },
  {
    "x": 0.8,
    "y": 0.7,
    "intensity": 0.4900980486407216,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.75,
    "intensity": 0.44773194914063696,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.8,
    "intensity": 0.4,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.85,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.8,
    "y": 0.9,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.8,
    "y": 0.95,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0,
    "intensity": 0.1368661749183967,
    "color": "#0a0e27"
  },
  {
    "x": 0.85,
    "y": 0.05,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0.1,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0.15,
    "intensity": 0.30000000000000004,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0.2,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.25,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.3,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.35,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.4,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.45,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.85,
    "y": 0.5,
    "intensity": 0.5050252531694168,
    "color": "#4169b0"
  },
  {
    "x": 0.85,
    "y": 0.55,
    "intensity": 0.5,
    "color": "#4169b0"
  },
  {
    "x": 0.85,
    "y": 0.6,
    "intensity": 0.48521849295065,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.65,
    "intensity": 0.4614835192865496,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.7,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.75,
    "intensity": 0.3917237469701781,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.8,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.85,
    "y": 0.85,
    "intensity": 0.30000000000000004,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0.9,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.85,
    "y": 0.95,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0,
    "intensity": 0.09446148618625838,
    "color": "#0a0e27"
  },
  {
    "x": 0.9,
    "y": 0.05,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.9,
    "y": 0.1,
    "intensity": 0.19999999999999996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.15,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.2,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.25,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.3,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.35,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.4,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.45,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.5,
    "intensity": 0.434314575050762,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.55,
    "intensity": 0.4299122874504311,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.6,
    "intensity": 0.41690481051547,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.65,
    "intensity": 0.3958477013202715,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.7,
    "intensity": 0.3675444679663241,
    "color": "#2d4575"
  },
  {
    "x": 0.9,
    "y": 0.75,
    "intensity": 0.33291679679368336,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.8,
    "intensity": 0.29289321881345254,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.85,
    "intensity": 0.24833518108135455,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.9,
    "intensity": 0.19999999999999996,
    "color": "#1a1f3a"
  },
  {
    "x": 0.9,
    "y": 0.95,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.95,
    "y": 0,
    "intensity": 0.048685120477977684,
    "color": "#0a0e27"
  },
  {
    "x": 0.95,
    "y": 0.05,
    "intensity": 0.10000000000000009,
    "color": "#0a0e27"
  },
  {
    "x": 0.95,
    "y": 0.1,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.95,
    "y": 0.15,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.2,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.25,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.3,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.35,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.4,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.95,
    "y": 0.45,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.95,
    "y": 0.5,
    "intensity": 0.36360389693210726,
    "color": "#2d4575"
  },
  {
    "x": 0.95,
    "y": 0.55,
    "intensity": 0.3596875762567151,
    "color": "#2d4575"
  },
  {
    "x": 0.95,
    "y": 0.6,
    "intensity": 0.34807975947973513,
    "color": "#2d4575"
  },
  {
    "x": 0.95,
    "y": 0.65,
    "intensity": 0.3291796067500631,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.7,
    "intensity": 0.3035805861407941,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.75,
    "intensity": 0.2719890110719482,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.8,
    "intensity": 0.23514707296108228,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.85,
    "intensity": 0.1937742251701451,
    "color": "#1a1f3a"
  },
  {
    "x": 0.95,
    "y": 0.9,
    "intensity": 0.14853068170368,
    "color": "#0a0e27"
  },
  {
    "x": 0.95,
    "y": 0.95,
    "intensity": 0.10000000000000009,
    "color": "#0a0e27"
  }
],
  timestamp: Date.now(),
};
