/**
 * ============================================================================
 * TradeOS Aura Map Generator
 * Generates visual aura mappings for user interactions and quests
 * ============================================================================
 */

import * as fs from 'fs';
import * as path from 'path';

interface AuraPoint {
  x: number;
  y: number;
  intensity: number;
  color: string;
}

interface AuraMap {
  id: string;
  points: AuraPoint[];
  timestamp: number;
}

/**
 * Generate gradient colors based on intensity
 */
function getAuraColor(intensity: number): string {
  const colors = [
    '#0a0e27', // Very low
    '#1a1f3a', // Low
    '#2d4575', // Medium-low
    '#4169b0', // Medium
    '#5a8de0', // Medium-high
    '#7db5ff', // High
    '#a0d0ff', // Very high
  ];
  
  const index = Math.floor(intensity * (colors.length - 1));
  return colors[Math.min(index, colors.length - 1)];
}

/**
 * Generate aura points for a standard grid
 */
function generateAuraPoints(gridSize: number = 20): AuraPoint[] {
  const points: AuraPoint[] = [];
  
  for (let x = 0; x < gridSize; x++) {
    for (let y = 0; y < gridSize; y++) {
      // Create wave-like intensity pattern
      const centerX = gridSize / 2;
      const centerY = gridSize / 2;
      const distance = Math.sqrt(Math.pow(x - centerX, 2) + Math.pow(y - centerY, 2));
      const maxDistance = Math.sqrt(2) * gridSize / 2;
      const intensity = 1 - (distance / maxDistance);
      
      points.push({
        x: x / gridSize,
        y: y / gridSize,
        intensity: Math.max(0, intensity),
        color: getAuraColor(intensity),
      });
    }
  }
  
  return points;
}

/**
 * Generate TypeScript utility file
 */
function generateUtilityFile(): void {
  const utilContent = `/**
 * Auto-generated Aura Map Utilities
 * Generated by scripts/auraMap.ts
 */

export interface AuraPoint {
  x: number;
  y: number;
  intensity: number;
  color: string;
}

export interface AuraMap {
  id: string;
  points: AuraPoint[];
  timestamp: number;
}

/**
 * Get aura color based on user level
 */
export function getAuraColorForLevel(level: number): string {
  if (level >= 10) return '#FFD700'; // Gold
  if (level >= 7) return '#7DB5FF';  // Bright blue
  if (level >= 5) return '#4169B0';  // Medium blue
  if (level >= 3) return '#2D4575';  // Dark blue
  return '#1A1F3A'; // Very dark blue
}

/**
 * Calculate aura intensity based on activity
 */
export function calculateAuraIntensity(
  trades: number,
  volume: number,
  lpScore: number
): number {
  const tradeWeight = 0.3;
  const volumeWeight = 0.4;
  const lpWeight = 0.3;
  
  const normalizedTrades = Math.min(trades / 100, 1);
  const normalizedVolume = Math.min(volume / 1000000, 1);
  const normalizedLP = Math.min(lpScore / 100, 1);
  
  return (
    normalizedTrades * tradeWeight +
    normalizedVolume * volumeWeight +
    normalizedLP * lpWeight
  );
}

/**
 * Generate aura gradient for canvas
 */
export function generateAuraGradient(
  ctx: CanvasRenderingContext2D,
  centerX: number,
  centerY: number,
  radius: number,
  intensity: number
): CanvasGradient {
  const gradient = ctx.createRadialGradient(
    centerX, centerY, 0,
    centerX, centerY, radius
  );
  
  const alpha = intensity * 0.8;
  gradient.addColorStop(0, \`rgba(125, 181, 255, \${alpha})\`);
  gradient.addColorStop(0.5, \`rgba(65, 105, 176, \${alpha * 0.6})\`);
  gradient.addColorStop(1, \`rgba(26, 31, 58, 0)\`);
  
  return gradient;
}

/**
 * Apply aura effect to element
 */
export function applyAuraEffect(
  element: HTMLElement,
  intensity: number,
  color?: string
): void {
  const auraColor = color || getAuraColorForLevel(Math.floor(intensity * 10));
  element.style.boxShadow = \`0 0 \${20 + intensity * 30}px \${auraColor}\`;
  element.style.border = \`2px solid \${auraColor}\`;
}

/**
 * Default aura map data
 */
export const defaultAuraMap: AuraMap = {
  id: 'default',
  points: ${JSON.stringify(generateAuraPoints(), null, 2)},
  timestamp: Date.now(),
};
`;

  const utilsDir = path.join(__dirname, 'frontend', 'utils');
  if (!fs.existsSync(utilsDir)) {
    fs.mkdirSync(utilsDir, { recursive: true });
  }
  
  const filePath = path.join(utilsDir, 'auraMap.ts');
  fs.writeFileSync(filePath, utilContent);
  console.log('✅ Generated frontend/utils/auraMap.ts');
}

/**
 * Generate aura configuration file
 */
function generateAuraConfig(): void {
  const config = {
    enabled: true,
    gridSize: 20,
    updateInterval: 5000,
    colors: {
      low: '#1a1f3a',
      medium: '#4169b0',
      high: '#7db5ff',
      legendary: '#ffd700',
    },
    effects: {
      glow: true,
      pulse: true,
      particles: false,
    },
  };

  const configPath = path.join(__dirname, 'config', 'aura.json');
  const configDir = path.dirname(configPath);
  
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  console.log('✅ Generated config/aura.json');
}

/**
 * Main execution
 */
function main(): void {
  console.log('🎨 TradeOS Aura Map Generator');
  console.log('=============================\n');

  console.log('📊 Generating aura utilities...');
  generateUtilityFile();

  console.log('⚙️  Generating aura configuration...');
  generateAuraConfig();

  console.log('\n✨ Aura map generation complete!');
  console.log('=============================\n');
}

main();
